name: 定时更新 README

on:
  schedule:
    - cron: '*/50 * * * *' # 每50分钟触发一次

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout 代码
      uses: actions/checkout@v2
      
    - name: 更新 README
      run: |
        # 更新 runtime.txt 文件
        echo "$(date '+%Y-%m-%d %H:%M:%S')" > runtime.txt

        # 提交更改到仓库
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "自动更新 runtime.txt"

        # 使用 GitHub 官方操作推送更改
        github_token: ${{ secrets.GITHUB_TOKEN }}
        git push
